PeopleList/Controllers/CityController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PeopleIndex.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;

namespace PeopleIndex.Controllers
{
   // [Authorize(Roles ="Admin")]
    public class CityController : Controller
    {
        private readonly AppDbContext _context;
        public CityController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Cities()
        {
            List<City> listOfCities = _context.Cities.Include(c => c.Country).ToList();
            return View(listOfCities);
        }
        public IActionResult Create()
        {
            ViewBag.Country = new SelectList(_context.Countries, "CountryId", "CountryName");
            return View();
        }
        [HttpPost]
        public IActionResult Create(City newCity)
        {
            if (ModelState.IsValid)
            {
                _context.Cities.Add(newCity);
                _context.SaveChanges();
                return RedirectToAction("Cities");
            }
            return View();
        }
        public IActionResult Remove(int cityId)
        {
            var deleteEntry = _context.Cities.Find(cityId);
            _context.Cities.Remove(deleteEntry);
            _context.SaveChanges();
            return RedirectToAction("Cities");
        }
    }
}

PeopleList/Controllers/CountryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using PeopleIndex.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PeopleIndex.Controllers
{
   // [Authorize(Roles = "Admin")]
    public class CountryController : Controller
    {
        private readonly AppDbContext _context;
        public CountryController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Countries()
        {
            List<Country> listOfCountries = _context.Countries.ToList();
            return View(listOfCountries);
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Country newCountry)
        {
            if (ModelState.IsValid)
            {
                _context.Countries.Add(newCountry);
                _context.SaveChanges();
                return RedirectToAction("Countries");
            }
            return View();
        }
        public IActionResult Remove(int countryId)
        {
            var deleteEntry= _context.Countries.Find(countryId);
            _context.Countries.Remove(deleteEntry);
            _context.SaveChanges();
            return RedirectToAction("Countries");
        }
    }
}

PeopleList/Controllers/LanguageController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

using PeopleIndex.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PeopleIndex.Controllers
{
    //[Authorize(Roles = "Admin")]
    public class LanguageController : Controller
    {
        private readonly AppDbContext _context;
        public LanguageController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Languages()
        {
            List<Language> listOfLanguages = _context.Languages.ToList();
            return View(listOfLanguages);
            
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Language newlanguage)
        {
            if (ModelState.IsValid)
            {
                _context.Languages.Add(newlanguage);
                _context.SaveChanges();
                return RedirectToAction("Languages");
            }
            return View();
        }
        public IActionResult Remove(int languageId)
        {
            var deleteEntry = _context.Languages.Find(languageId);
            _context.Languages.Remove(deleteEntry);
            _context.SaveChanges();
            return RedirectToAction("Languages");
        }
    }
}

PeopleList/Controllers/PeopleController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

using PeopleIndex.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace PeopleIndex.Controllers
{
    public class PeopleController : Controller
    {
        private readonly AppDbContext _context;
        public PeopleController(AppDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
           List<Person> listOfPeople=_context.People
                .Include(c => c.City)
                .Include(l => l.Languages)
                .ToList();

           return View(listOfPeople);
        }
        [HttpPost]
        public IActionResult Index(string search)
        {
            
            var searchPeople =  from ppl in _context.People.Include(c => c.City)
                                where ppl.City.CityName == search || ppl.Name == search
                                select ppl;

            return View(searchPeople);
        }
        public IActionResult Create()
        {
            ViewBag.City = new SelectList(_context.Cities, "CityId", "CityName");
            ViewBag.Language = new SelectList(_context.Languages, "LanguageId", "LanguageName");
            return View();
        }
        [HttpPost]
        public IActionResult Create(Person newPerson)
        {
            if (ModelState.IsValid)
            {
                _context.People.Add(newPerson);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View();
        }
        public IActionResult Remove(int id)
        {
            var deleteEntry=_context.People.Find(id);
            _context.People.Remove(deleteEntry);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        /*[HttpPost]
        public IActionResult Order(string order)
        {
            if (order == "ascending")
            {
                var orderByAscendingPeople = from ppl in _context.People
                                                 //where ppl.City == search || ppl.Name == search
                                             orderby ppl.Name ascending
                                             select ppl;
                return View(orderByAscendingPeople);
            }
            else
                return RedirectToAction("Index");
        }*/
    }
}

PeopleList/Views/Shared/_CityCard.cshtml
@model City

<div class="row">
    <div class="col-sm">
      @Model.CityId
    </div>
    <div class="col-sm">
      @Model.CityName
    </div>
    <div class="col-sm">
      @Model.Country.CountryName
    </div>
    <div class="col-sm">
        <a asp-action="Remove" asp-route-cityId="@Model.CityId">Remove</a>
    </div>
</div>

PeopleList/Views/Shared/_CountryCard.cshtml
@model Country

<div class="row">
    <div class="col-sm">
      @Model.CountryId
    </div>
    <div class="col-sm">
      @Model.CountryName
    </div>
    <div class="col-sm">
        <a asp-action="Remove" asp-route-countryId="@Model.CountryId">Remove</a>
    </div>
</div>

PeopleList/Views/Shared/_LanguageCard.cshtml
@model Language

<div class="row">
    <div class="col-sm">
      @Model.LanguageId
    </div>
    <div class="col-sm">
      @Model.LanguageName
    </div>
    <div class="col-sm">
        <a asp-action="Remove" asp-route-countryId="@Model.LanguageId">Remove</a>
    </div>
</div>

PeopleList/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/lib/bootstrap/css/bootstrap.css" rel="stylesheet" />
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
</head>
<body class="bootstrap-dark">
    <nav >
        <ul class="nav justify-content-center">
            <partial name="_LoginPartial" />
            <li class="nav-item">
                <a class="nav-link" asp-controller="People" asp-action="Index">Home</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="City" asp-action="Cities">Cities</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Country" asp-action="Countries">Countries</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Language" asp-action="Languages">Languages</a>
            </li>
        </ul>
    </nav>
    <div class="container">
        @RenderBody()
    </div>
    @RenderSection("Scripts", required:false)
</body>

</html>

PeopleList/Views/Shared/_PersonCard.cshtml
@model Person

<div class="row">
    <div class="col-sm">
      @Model.PersonId
    </div>
    <div class="col-sm">
      @Model.Name
    </div>
    <div class="col-sm">
      @Model.City.CityName
    </div>
    <div class="col-sm">
      @Model.PhoneNumber
    </div>
    <div class="col-sm">
      @Model.Languages
    </div>
    <div class="col-sm">
        <a asp-action="Remove" asp-route-id="@Model.PersonId">Remove</a>
    </div>
    <div class="col-sm">
        <a asp-action="Edit" asp-route-id="@Model.PersonId">Edit</a>
    </div>
</div>